Pannkoogid/urls.py
from django.contrib import admin
from django.urls import path
from lehed.views import IndexView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view()),
]

lehed/models.py
from django.db import models


class MenuItemCategory(models.Model):
    title = models.CharField(max_length=200)
    image_side = models.ImageField(default='#')

    def __str__(self):
        return self.title


class MenuItem(models.Model):
    title = models.CharField(max_length=200)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    category = models.ForeignKey(MenuItemCategory, on_delete=models.CASCADE)

    def __str__(self):
        return self.title


class Address(models.Model):
    street = models.CharField(max_length=128)
    state = models.CharField(max_length=128)
    country = models.CharField(max_length=128)
    index = models.PositiveIntegerField()
    latitude = models.DecimalField(max_digits=20, decimal_places=10)
    longitude = models.DecimalField(max_digits=20, decimal_places=10)

    def __str__(self):
        return f"{self.street}, {self.state}, {self.country}, {self.index}"


class Location(models.Model):
    title = models.CharField(max_length=200)
    address = models.ForeignKey(Address, on_delete=models.CASCADE)

lehed/views.py
from django.views.generic import ListView
from lehed.models import MenuItemCategory


class IndexView(ListView):
    model = MenuItemCategory
    template_name = 'index.html'

lehed/templates/index.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <a href="#description"><button id="to-description" type="button" class="btn btn-primary"><i class="fas fa-arrow-down fa-3x nav-icon"></i></button></a>

    <div id="map" class="container-fluid h-100"></div>

    <a href="#menu-1"><button id="to-menu" type="button" class="btn btn-secondary"><i class="fas fa-arrow-down fa-3x nav-icon"></i></button></a>

    <div id="description" class="container-fluid h-100">
        <table id="description-table" class="h-100 w-50 mx-auto">
            <tbody>
                <tr>
                    <td><p id="description-title">Parimad koogid sünnivad siin</p><p id="description-text">{% lorem 2 %}</p></td>
                </tr>
            </tbody>
        </table>
    </div>

    {% for category in menuitemcategory_list %}
    <div id='menu-{{ forloop.counter }}' class="container-fluid menu {% cycle 'even' 'odd' %} h-100">
        <div class="row">
            <div class="col-6">
                <img src="{% static "images/pannkook_soolane.svg" %}" alt="" class="img-700 mx-auto">
            </div>
            <div class="col-6">
                <table class=" h-100 w-75">
                    <tbody>
                        <tr>
                            <td>
                                <span class="title-font item-title {% cycle 'title-even' 'title-odd' %}">{{ category.title }}</span>
                                <table class="w-75 menu-table">
                                    <tbody>
                                        {% for item in category.menuitem_set.all %}
                                        <tr><td class="item-food-title">{{ item.title }}</td>
                                            <td class="item-price">{{ item.price }}€</td>
                                        </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <div class="row">
            <a href="#menu-{{ forloop.counter|add:"1" }}" class="mx-auto menu-arrow"><button type="button" class="btn btn-secondary menu-number-down"><i class="fas fa-arrow-down fa-3x nav-icon"></i></button></a>
        </div>
    </div>
    {% endfor %}


{% endblock content %}
{% block javascript %}
    <script src="https://unpkg.com/leaflet@1.4.0/dist/leaflet.js"></script>
    <script src="{% static "js/leaflet-providers.js" %}"></script>
    <script>
        var map = L.map('map',{
            scrollWheelZoom: false,
            zoomControl: false,
            layers:[]
        }).setView([59.426962, 24.741554], 14);

        L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
            attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
        }).addTo(map);

        L.marker([59.443573, 24.73144]).addTo(map)
            .bindPopup('<div class="popup-title title-font font-weight-bolder">Pärnu maantee maja</div><div class="row"><div class="col-6"><img src="{% static "images/pannkook.svg" %}" width="60px" class="center-img"></div><div class="col-6"><ul style="padding:10px;list-style-type: none;"><li><small>Pärnu maantee 99, Tallinn</small></li><li><small>E-R</small></li><li><small>9:00-18:00</small></li></ul></div></div>')
            .openPopup();
        L.marker([59.412264, 24.73559]).addTo(map)
            .bindPopup('<div class="popup-title title-font font-weight-bolder">Tondi maja</div><div class="row"><div class="col-6"><img src="{% static "images/pannkook.svg" %}" width="60px" class="center-img"></div><div class="col-6"><ul style="padding:10px;list-style-type: none;"><li><small>Tondi 66, Tallinn</small></li><li><small>E-R</small></li><li><small>9:00-18:00</small></li></ul></div></div>',)
            .openPopup();
        L.tileLayer.provider('Stamen.TonerLite').addTo(map);

        L.control.zoom({
             position:'middleleft'
        }).addTo(map);
    </script>
{% endblock javascript %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Pannkoogid</title>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.4.0/dist/leaflet.css" />
    <link rel="stylesheet" type="text/css" href="{% static "css/project.css" %}">

    <link href="https://fonts.googleapis.com/css?family=Cabin" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Ubuntu" rel="stylesheet">

</head>
<body>
    <a href="#navbar"><img src="{% static "images/pankoogid_ratas2.svg" %}" alt="pancakes_icon" id="navbar-image"></a>
    <div id="navbar" class="w-100">
        <div id="navigation">
            <div class="row mb-3 align-content-end">{% csrf_token %}<input class="form-control ml-auto" type="search" placeholder="Otsing" aria-label="Search"></div>
            <div class="row mb-3 align-content-end"><a href="#description"><button type="button" id="navbar-button-description" class="btn btn-info">Veidi meie restoranist</button></a></div>
            <div class="row"><a href="#menu"><button type="button" class="btn btn-info">Maiuspalade menüü</button></a></div>
        </div>
    </div>

    {% block content %}
    {% endblock content %}

    <div id="footer">
        <p id="footer-center" class="title-font">
            <a href="">01234567</a>
            <span class="ml-1 mr-1">|</span>
            <a href="">Email</a>
            <span class="ml-1 mr-1">|</span>
            <a href="">Privacy policy</a>
        </p>
    </div>


    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    {% block javascript %}
    {% endblock %}
</body>
</html>